# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Code' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'UIScrollView-InfiniteScroll', '~> 1.1.0'
   pod 'SVProgressHUD'
  # Pods for Code

  target 'CodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CodeUITests' do
    # Pods for testing
  end

end
